### ISSUE TITLE
Deep-Learning model development

### ISSUE THREAD

**Issue by FarmingWon** [FarmingWon/CcTv-Carbon-consumption-Trace-Visualize#10]
- [ ] 4월 개발 계획
- 실험을 위한 딥 러닝 모델 개발
- 1주차 : VGGNet[완료]
- 2주차 : VGGNet 학습 중 소모되는 하드웨어 자원 정보 저장 모듈 및 체크포인트를 사용한 딥 러닝 재현 테스트[완료]
- 3주차 : 웹 기반 Carbon Management System(CMS) 개발
- 4주차 : 중간 발표

**Comment by jhparkland** [comment]
2주차 개발 계획이 궁금하네요

**Comment by FarmingWon** [comment]
피드백 감사합니다.
2주차 개발 계획은 구체적으로 Firebase에 체크포인트 저장 및 해당 체크포인트를 이용한 딥 러닝 재현을 테스트 하였습니다.
그리고 실시간으로 하드웨어 자원에 대한 정보 수집까지 개발을 완료하였습니다.
